# Generated by Django 6.0.4 on 2026-04-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_assistant', '0003_chatmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
