# Generated by Django 6.0.4 on 2026-04-20 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_assistant', '0004_chatsession_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'โสด'), ('Married_No_Income', 'สมรส (คู่สมรสไม่มีรายได้)'), ('Married_With_Income', 'สมรส (คู่สมรสมีรายได้)')], default='Single', max_length=50)),
                ('children_before_2018', models.IntegerField(default=0)),
                ('children_after_2018', models.IntegerField(default=0)),
                ('parents_care_count', models.IntegerField(default=0)),
                ('disabled_care_count', models.IntegerField(default=0)),
                ('monthly_base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
