# Generated by Django 6.0.4 on 2026-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_assistant', '0007_communitypost_communitycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ui_component',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ui_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
